### PR TITLE
Add function support

### PR DESCRIPTION
**Pull request by VinGarcia**
Hello @bamos, I said I would stop working on it, but the function support was something that I could do and was not specific to my case.

I hope you like the addition. This fullfill the issue #20.

The additions are:
- Catch.o now is compiled separated from the main test file, (this makes the compilation time for tests a lot faster)
- Support to built-in functions, I have added: print(), sin(), cos(), tan() and pow()
- Support to built-in function with multiple parameters, pow() for instance accept 2 arguments.

I have also added a new type the TUPLE. I use it to join together multiple parameters into a single object.
To built it I transformed the character "," into an operator that builds tuples.

Regards.

Just a note: The function system still have some small issues:
- Functions with no arguments are probably going to break the system.
- Excess of parameters is not handled and so on.

I need to work a little more on it so it gets more reliable.

### CODE REVIEW

**Comment by bamos** [comment]
Thanks @VinGarcia - these features are awesome! I hope you like using Catch for the tests, I'm still happy with it. Can you also fix the Travis build for this?

-Brandon.

**Comment by VinGarcia** [comment]
Yep, I'm loving Catch. I'm even using it on another project and replacing a lot of old tests =].

Just fixed the Travis build, I was excited to show you the changes and forgot about it =P.

**Comment by bamos** [comment]
Awesome, thanks! You've added so many cool features. I was easily able to add an absolute value function to resolve #2. Soon, I'll update the README with your new features and also slightly change the Makefile to create a library so it's easier to use.

By the way, I noticed that removing the `vars` from `calculate` gives the following error:

```
REQUIRE(calculator::calculate("sqrt(4)").asDouble() == 2);
```

with the message:

```
Unable to find the variable 'sqrt'.
```

-Brandon.

**Comment by VinGarcia** [comment]
Oh thanks to remembering me about that. Can you fix it for me? (so we avoid another merge) The problem is on the constructor Scope::Scope() {}, it should be like:

Scope::Scope() {
  // Add default functions to the global namespace:
  scope.push_front(&Function::default_functions);
}

**Comment by bamos** [comment]
Thanks, added with a C++11 feature. I also added a C++11 flag to the Makefile.

**Comment by bamos** [comment]
Actually the g++ version on Travis is outdated and doesn't support the feature I used, so I just added what you suggested and removed C++11 (for now). C++11 has a lot of great features and I am fine having it as a dependency as long as Travis supports the features we want to use.

**Comment by bamos** [comment]
Sorry for bouncing here, I just re-added C++11 and updated the gcc on Travis to 4.8.

**Comment by VinGarcia** [comment]
That's fine for me, I also like the C++11 features. I was just wondering if this would not force an user of our library to also compile with C++11, or if the .o files are compatible.

**Pull request merged**
