### PR TITLE
A lot of updates for it to work better as a library

### PR DESCRIPTION
**Pull request by VinGarcia**
Note: This pull request can't be merged automatically, if you prefer I can fix this and submit a new request.

@bamos I did a lot of additions (working like a crazy person before my deadline xP) but I worry if I am not making your framework more complex than what you intended it to be.

Currently I am working in 2 branches the first one (my master branch) I am keeping all the commits that seem important to send back to you, and on the second branch I am adding features specific to the programming language I'm making for my thesis.

Also you are invited to take a look! as its starting to take a [form](https://github.com/VinGarcia/cpp-code-parser). It already works with `user-defined-functions`, `for-in loops` and `if-statements`. The main part (the thesis part is not integrated yet).

Well I have a lot to discuss. First the changes:

* Now calculator::calculator is fit to work as a slave parser, I hope this is a good name; Now it have an optional argument to say which characters should be treated as delimiters and also accept a char** so it can report back the last position of `expr` before it stop parsing.

This way one can use it inside another parser without having to understand the internal logic of the calculator.

* Now the Scope::default_functions variable became Scope::default_global, so that it will always be the global scope of any Scope instance even an empty one. And I added some support so the user can add its own functions and objects to it. For example I added a `global` map to the global scope, so that an user can make such a statement:
  - global.foo = 'bar'

* Add support for ' \n and \t ' so the final user can write these strings as they would in python or javascript.

* Messed a lot with the Function type, now it work in more cases, has less bugs and is easily extensible.

* A lot of small refactors, and bug fixing. Also added new tests for detecting these bugs.

The other stuff I would like to talk is about my other project that's using yours as a submodule. But we can talk about it after deciding if this pull request is fine.

- VinGarcia

### CODE REVIEW

**Comment by bamos** [comment]
Thanks, manually merged! I love these kinds of improvements, please keep sending them. Can you pull back the latest master so our code bases are consistent again? I don't plan on making any more changes for a while.

-Brandon.

**Comment by VinGarcia** [comment]
Done it!

**Comment by VinGarcia** [comment]
@bamos can I have your opinion on my new language?

My thesis is on natural language processing. I have built an interesting tool for breaking a given text into variables so you can extract meaning from it.

Simple speaking its an extended regular expression tool with recursion and some other stuff that I believe will offer us a programming language that is adequate for dealing with the complexity of human language.

The problem is: Alone it is just a language with an ugly syntax and bad support to do anything.

So I needed to create a way to give it better support, that's why I started working on this project. But its growing bigger and better than I expected, I'm really liking this code. So I'm planning on making it a full featured programming language, and inserting my tool (its name is Talkin) as a built-in feature of the language.

So, I'm explaining all that because I would be glad to get any suggestions or ideas you come up with =]. 

I'll show a sample of what I am planning on:

```javascript
// Functions like javascript:
function f_name(a, b, c) {
  // The same meaning for `this` as Javascript implies:
  this.foo = "bar";
}

// Object declaration as JSON:
obj = { func: f_name, my_list: [1,2,3] }
obj.func()

// Default stdout command is print instead of console.log:
print( obj.foo ) // "bar"

// Loops as a mixture of Python and Javascript:
for(c in ['a', 'b', 'c']) print( i ) // Would print the values of the list not index as in JS.
// Also note that in the loop above the variable `c` would be declared in local scope
different from JS.
// While loops:
while( cond ) { ... }

// Built-in support for generators from the start:
for(idx, value in enumerate(range(10,1,-1))) {
  print(value) // 0 1 2 3 4 5 6 7 8 9
  print(value) // 10 9 8 7 6 5 4 3 2 1
}

// Also note the python unpacking that was used on the loop above:
a, b = (1, 2)
```

About generators there is more to discuss, I think it would be a good idea to allow
user defined generators from the beginning as well:
```
// User defined generators in a way I think is elegant and explicit:
generator my_gen() {
  while( cond ) {
    if ( stuff ) {
      yield foo;
    } else { return last_foo; }
  }
}
// Using `yield` for intermediary results, and `return` to end the loop like Python, but
// using an explicit name `generator` to declare it.

// usage:
for(value in my_gen()) { ... }
```

So this would be the basic syntax. The `;` would be options as it is in both languages and indentation will not be part of the syntax as it is in Python.

About classes and/or prototype inheritance I thinking that they can coexists in a very simple way:

```javascript
my_class = {
  attr1 : "My first class",
  __init__ : function(arg1, arg2) { a = arg1, this.b = arg2 }
  getA : function() { return private['a']; }
}
```

There is a lot going on up there:
1. __init__ is the constructor, but it is also a normal attribute.
2. note that `a = arg1` is declared inside init, all the variables of the init function namespace will
be available for other functions of the same object under the name "private"
3. Function getA can access the variable `a` as: private['a'] or private.a

Now the instantiation:
```javascript
instance = new my_class("private", "public");
```
Here the __init__ function will be executed, but note that different from JS the key-work `new`
is not used on functions, but in Objects. It will work even if the object has no __init__ function.

Lets check out this instance:
```javascript
print(instance)
{ "b" : "public" }
// print object inherited from the prototype object:
print( instance.attr1 ) // "My first class"

// call a method inherited from the prototype object:
print( getA() ) // would print "private"
```
Note that in the above call the getA was defined on the prototype of the class, but it received a reference to the "private" object that contains the variable `a` when it was called.

The main differences between this and the normal Javascript prototype inheritance are:
1. The role of the __init__ function is very clear
2. There is a private scope that the other functions of the prototype can have access (much like the access they have to `this`)
3. All functions would have access to a super function, that would any function that was overwritten by them.

I like this model because I think it really covers everything you need in a class and also offer the flexibility of the prototype inheritance when needed, what do you think?

Also sorry for writting it all, but I needed to, I've had all these ideas and no one to talk =/.

Thank you for reading, if you have any suggestion, or advice I'll be happy =]. Also if you want you can show it to someone that might have interest in contributing.

**Comment by bamos** [comment]
Hi @VinGarcia - very interesting! I would have never guessed when I created this project that somebody would use it for expression parsing in a programming language. I'll think more about this.

-Brandon.

**Pull request merged**
