### PR TITLE
Some refactoring and bug fixing

### PR DESCRIPTION
**Pull request by VinGarcia**
Other than some minor refactoring and some bug fixing, there is one new feature:

- Add support to parser to work as a slave parser.

i.e. now the calculator constructor accepts two optional new arguments: a delimiters list, that will define when it should stop parsing. And a pointer to a char* so it can report back the last position it were on the text when it found the delimiter or end of string character.

This way it can be used by another parser to parse some types of expressions. Leaving statements like for loops and if statements in charge of other parser.

I've added this to allow me to use this implementation as part of a programming language.

Also, the memory leak I fixed was introduced by me when I added the assignment operator, and I forgot to test it with valgrind. Is there a way to add a valgrind test for mem leak on travis? So we don't let this problem arise again?

Edit: 
Also fixed the problem of calling a function with 0 arguments.
I replaced the unexistent argument for NoneToken until I find a better solution.

Also added support for the user to escape special characters on string literals, e.g.:
calculator::calculate("foo\\\\nbar").asString == "foo\nbar"

### CODE REVIEW

**Comment by bamos** [comment]
Awesome, thanks @VinGarcia!

**Comment by VinGarcia** [comment]
=], I am now starting a program language based on this project.

I will keep sending commits but I'll keep a separated branch with the more specific features.

If you prefer I may send them as well.

My project is about a programmable text processor aimed to process human typed unformatted text. The code is made of two parts:

1. Pattern matching (thats the innovative part of the system)
2. A programming language to deal with the preprocessed text.

And I think it will be interesting =].

I am planning the language to be a mix between Python and Javascript features.

The code is still private, because the old code (the part I wrote as a BS) is very ugly =/. But as soon as I clean it up and translate all comments to english I'll make it open-source and tell you =].

**Comment by bamos** [comment]
Yes sounds interesting! Excited to see what direction you take the project. If possible, it could be nice for you to have your project as its own repo in your profile that uses this repo as a library. Happy to accept PRs to help with this.

Hope the project goes well!

-Brandon.

**Comment by VinGarcia** [comment]
Thanks!, that's the plan, I'll keep adding as much stuff as I can to your project while still keeping it as a framework, and use it as a base for my own project. Sorry for the delay to answer =P

**Pull request merged**
